### ISSUE TITLE
Excel addin?

### ISSUE THREAD

**Issue by aleave** [TabularLang/CoreTabular#9]
Hi, is there still a way to have this as an excel addin ?

thanks

**Comment by crusso** [comment]
Hi Alessandro,

The project page appears to have disappeared but you can still download  a binary from here:

http://download.microsoft.com/download/9/4/C/94CD7FD6-0DD9-4CAD-AE62-4C3E79162DC6/Tabular.zip

Cheers,
Claudio

**Comment by aleave** [comment]
Thanks Claudio!
